# Generated by Django 5.1.7 on 2025-03-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('planned_date', models.DateField(verbose_name='Планируемая дата')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукция')),
            ],
        ),
    ]
