# Generated by Django 5.1.7 on 2025-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем (л/кг)')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('production_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
            ],
        ),
    ]
